# Generated by Django 3.0.4 on 2020-10-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.TextField(db_column='eng')),
                ('ru', models.TextField(db_column='ru')),
                ('eng_value', models.TextField(db_column='eng_value')),
            ],
        ),
        migrations.CreateModel(
            name='RelateGuidId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='guid', max_length=120)),
                ('w', models.ForeignKey(db_column='w', on_delete=django.db.models.deletion.CASCADE, to='Sub1C.Word')),
            ],
        ),
    ]
